### ISSUE TITLE
Is this example still works? System.ArgumentException: Illegal characters in path

### ISSUE THREAD

**Issue by MrNovado** [copygirl/howto-example-mod#3]
Hello there! Very nice tutorial, but I'm getting a fatal error on running from a `Launch Client (.NET)` option on windows. Not very descriptive error, so I'm not exactly sure where is it coming from.

Your other mod CarryCapacity run just fine tho.
```
[Client Fatal] System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at _ACcessuzcTZFh8w9fQWFBeuWppn._uFJNfDZb4l56RynGHTDUY404beL(String , String& , Boolean , Boolean )
   at Vintagestory.Common.GameDatabase.ProbeOpenConnection(String databaseFilename, Int32& foundVersion, String& errorMessage, Boolean& isReadonly)
   at Vintagestory.Server.ServerSystemLoadAndSaveGame.OnBeginConfiguration()
   at Vintagestory.Server.ServerMain.EnterRunPhase(EnumServerRunPhase runPhase)
   at Vintagestory.Server.ServerMain.Launch()
   at _hCuHXesCXlp0LGSdrsPFpw4up5n._ZNXEC6XI5SVtqKMary7JKG8uq8c()
```

**Comment by copygirl** [comment]
The mod still runs for me even after all this time. It could have something to do with the environment variables `VINTAGE_STORY` and `VINTAGE_STORY_DATA`. Did you perhaps not set them, set them incorrectly, or did not properly replace them with hardcoded paths (if you decided you did not want to use environment variables)?

**Comment by MrNovado** [comment]
@copygirl yeah, I did set them, figured it would be less painful than pasting the abs-path all the time; and the CarryCapacity mod compiled and run, so it has to be something else? I'll try to compare them in more detail, I just wondered if maybe you bumped into something like this already.

**Comment by copygirl** [comment]
Well, looking into it, I guess it might have to do with the `--openWorld` argument in the `launch.json`. Does it work without it? Not quite sure why this is happening. Is it the quotation marks it tries to parse as part of the world name? What happens if you remove them?

**Comment by MrNovado** [comment]
@copygirl okay, it seems like I've found the reason why it doesn't work. It's because of the escaping characters in arguments to a launch task:

This crashes the server:
```
[
    "--playstyle=\"surviveandbuild\"",
    "--openWorld=\"modding test world.vcdbs\"",
    "--addOrigin", "${workspaceFolder}/resources/assets",
]
```

But this one works (from your vs-workspace example):
```
[
    "-p3", "--openWorld", "modding test world.vcdbs",
    "--addOrigin", "${workspaceFolder}/resources/assets"
]
```

And this one works as well:
```
[
    "--playstyle", "surviveandbuild",
    "--openWorld", "modding test world.vcdbs",
    "--addOrigin", "${workspaceFolder}/resources/assets"
]
```

Case closed :) Not sure how one supposed to escape characters on windows in this case (maybe you shouldn't?), but whatever.

**Comment by MrNovado** [comment]
Yeah, it seems it was quotation-marks-thing all along. Oh, Windows and Linux path-resolution conflicts... always making it difficult : )

I'll close the issue now, thank you for your time!

**Comment by copygirl** [comment]
Alright. Thank you! :green_heart: I will update the repo to fix that.

**Comment by copygirl** [comment]
And it appears that you need to remove the `.vcdbs` or else you'll end up with a `.vcdbs.vcdbs` file.
