### ISSUE TITLE
type: shell => type: process for Windows Users

### ISSUE THREAD

**Issue by DavidCarlyn** [copygirl/howto-example-mod#4]
Hello! Thanks for the great tutorial, but I found myself on an infinite building loop when setting this up on VSCode on the Windows 10 OS. In the end, I found that changing the "type" in tasks.json from "shell" to "process" fixed my issue. I'm new to C# development, but I think this may be worth mentioning in the README.md.

Thanks!

**Comment by copygirl** [comment]
Thank you for pointing this out to me. Looks like it still runs fine on linux with `process` as well so I went ahead and changed it.
