### ISSUE TITLE
--playStyle is incorrect in launch.json

### ISSUE THREAD

**Issue by chriswa** [copygirl/howto-example-mod#5]
Firstly, thank you so much for this repo! I was struggling with the incomplete "getting started with Visual Studio on Windows" Vintage Story wiki article and this is so much better. And I get to use my favourite IDE too. :D

I found only one issue when getting started with your repo: I believe `--playStyle` in `launch.json` should be `preset-surviveandbuild`, not `surviveandbuild`, as per https://wiki.vintagestory.at/index.php?title=Client_startup_parameters

This issue also affects `README.md`.

Thanks again!

**Comment by copygirl** [comment]
Thank you for letting me know.

There's also been something wrong with the launch parameters that are supposed to automatically open a world. Not sure if it's Linux only but I don't want to look into that today.
